export default {
    products: [
        {
            _id: '1',
            name:'ANMM Mulheres sexy Crop Tops Basic Slim',
            category: "Shirts",
            Image: '/images/product-1.jpg',
            price: 60,
            brand: 'Hiskywin',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: '2',
            name:'Full Zip Running Shirts',
            category: "Shirts",
            Image: '/images/product-1.jpg',
            price: 60,
            brand: 'Hiskywin',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: '3',
            name:'Full Zip Running Shirts',
            category: "Shirts",
            Image: '/images/product-1.jpg',
            price: 60,
            brand: 'Hiskywin',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: '4',
            name:'Full Zip Running Shirts',
            category: "Shirts",
            Image: '/images/product-1.jpg',
            price: 60,
            brand: 'Hiskywin',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: '5',
            name:'Full Zip Running Shirts',
            category: "Shirts",
            Image: '/images/product-1.jpg',
            price: 60,
            brand: 'Hiskywin',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: '6',
            name:'Full Zip Running Shirts',
            category: "Shirts",
            Image: '/images/product-1.jpg',
            price: 60,
            brand: 'Hiskywin',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
    ],
};