export default {
    products: [
        {
            _id: '1',
            name:'ANMM Mulheres sexy Crop Tops Basic Slim',
            category: "Shirts",
            Image: '/images/product-1.jpg',
            price: 100,
            brand: 'Hiskywin',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: '2',
            name:'Kit 3 Camisa Masculina Slim Social Manga',
            category: "Shirts",
            Image: '/images/product-2.jpg',
            price: 100,
            brand: 'Hiskywin',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: '3',
            name:'Legging 4 Estações Suplex Básica Fitness Academia',
            category: "Pants",
            Image: '/images/product-3.jpg',
            price: 100,
            brand: 'Hiskywin',
            rating: 5.0,
            numReviews: 7,
            countInStock: 6,
        },
        {
            _id: '4',
            name:'Akit 4 regatas femininas tapa bumbum',
            category: "Shirts",
            Image: '/images/product-4.jpg',
            price: 100,
            brand: 'Hiskywin',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: '5',
            name:'Bermuda Masculina Corrida Treino',
            category: "Shorts",
            Image: '/images/product-5.jpg',
            price: 100,
            brand: 'Hiskywin',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: '6',
            name:'Full Zip Running Shirts',
            category: "Shirts",
            Image: '/images/product-1.jpg',
            price: 60,
            brand: 'Hiskywin',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
    ],
};